### PR TITLE
Set userinfo from es-url in the HTTPURLConnection

### PR DESCRIPTION
**Pull request by Tetha**
Hey,

we were having trouble getting stagemonitor to work in our setup:

 - Elasticsearch runs on a heavily firewalled server
 - Apache has a ProxyPass '/elasticsearch' to localhost:9200
 - The ProxyPass requires authentication by basic auth

After some digging, user-info from the URL didnt appear to be moved into the HTTPUrlConnection in your util class. I've fixed that in a small change.

I'm not 100% certain if I changed all necessary files, but with this change, stagemonitor works in our setup. :)

Cheers.

### CODE REVIEW

**Comment by felixbarny** [comment]
Nice! The only problem is that the `java.util.Base64` class is only available on Java 8+ but stagemonitor aims to be Java 6 compatible.

**Comment by Tetha** [comment]
Right, I didn't realize that. We're running on Java 8 here, so this worked fine.

I've switched this to sun.misc encoders for now -- given that you're using a bunch of sun apis in the project already. So, this should run on Java 6 now - I can't test this right now.

BTW, you should check your coveralls integration - it's not allowed to pull the source, so I can't check if I should write unit-tests for this. It looks like that could be a bit more tricky.

**Comment by felixbarny** [comment]
The places where I do use the sun apis are guarded which means there is a fallback if the classes are not present. So I'd be more happy if you'd use `javax.xml.bind.DatatypeConverter#printBase64Binary`.

**Comment by Tetha** [comment]
There we go. I didn't see that particular implementation - my Java6 is kinda rusty at the moment ;)

**Comment by felixbarny** [comment]
Mine as well to be honest but StackOverflow for the win 😆

**Comment by felixbarny** [comment]
Oops, I completely forgot about that. Could you [sign the cla](https://github.com/stagemonitor/stagemonitor/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla)?

Thanks a bunch for your contribution 👍

**Comment by Tetha** [comment]
I have opened #227 for that.

**Comment by felixbarny** [comment]
Stagemonitor 0.31.0 is now available on maven central. Happy monitoring!

**Pull request merged**
