### PR TITLE
Add support for reporting spans to Zipkin

### PR DESCRIPTION
**Pull request by felixbarny**
/cc @adriancole

### CODE REVIEW

**Comment by adriancole** [comment]
coool... so advice on how to test?

**Comment by felixbarny** [comment]
I'll notify you as soon as its ready to test

**Comment by felixbarny** [comment]
Hi @adriancole,

I have set up an example application using Spring Boot: https://github.com/stagemonitor/boot-zipkin. I'd appreciate feedback a lot!

Stagemonitor's call trees blow up the details view in Zipkin. Is there a possibility to render `call_tree_ascii` in a `<pre>` tag? Also, the Address seems strange.

stagemonitor-zipkin

**Comment by adriancole** [comment]
thanks checking it out now

**Pull request merged**
