### PR TITLE
Support for Vert.x

### PR DESCRIPTION
**Pull request by glamarre360**
I've created a plugin for supporting vert.x server. It's done to the best of my knowlege and understanding of your project. If you have questions just ask me.

### CODE REVIEW

**Comment by felixbarny** [comment]
Wow, thank you so much for your epic pull request!

However, I will need some time to understand and test it. My current priority is to get the distributed tracing thing ready for release. Just thinking out loud, but maybe it would make sense to put this plugin in a separate repository where it can mature before making it a "official" part of stagemonitor? What do you think about that? Also, could you make an example project which I can use to test this and maybe to use as a template for integration tests?

P.S.: Do you have an idea how to realize the in browser widget for Vert.x?

**Comment by domtoupin** [comment]
Hi @felixbarny !

Just to let you know that @glamarre360 has completed his internship with us and thus the responsibility for this PR has been transferred to me. I will attempt to answer your questions in a near future and also improve/rework parts of the PR since I spotted a few glitches.

**Comment by felixbarny** [comment]
Thx for the heads up.

I haven't looked at the PR in too much detail but I've noticed one thing that maybe could be improved. At the moment, users have to configure which implementation of certain Vert.x interfaces they are using, for example `stagemonitor.vertx.eventbus.messageConsumerImplementation`. Wouldn't it be possible to instrument all implementations so that ideally the user does not have to configure anything?

**Comment by domtoupin** [comment]
Concerning your last questions, that is indeed one of the things I wanted to look at ;-)

**Comment by felixbarny** [comment]
Are you still working on this? I'm closing this for now because as I said, I'd like this to mature in an own repository first. Maybe it would make sense to create a stagemonitor/stagemonitor-contrib repository for that but for now just create your own repo.

**Pull request closed without merging**
