### PR TITLE
Prometheus fix

### PR DESCRIPTION
**Pull request by felixbarny**
@marcust I've combined your approach with the suggestions from @brian-brazil (thx for that).
Now we only have to manually de-duplicate for gauges.

### CODE REVIEW

**Comment by felixbarny** [comment]
Wait, that still does not work when reporting two timers :/

**Comment by felixbarny** [comment]
```
# HELP timer_seconds Generated from stagemonitor metric import (metric=timer, type=com.codahale.metrics.Timer)
# TYPE timer_seconds summary
timer_seconds_count{foo="baz",} 1.0
timer_seconds_sum{foo="baz",} -1.0
timer_seconds{foo="baz",quantile="0.5",} 0.001276479
timer_seconds{foo="baz",quantile="0.75",} 0.001276479
timer_seconds{foo="baz",quantile="0.95",} 0.001276479
timer_seconds{foo="baz",quantile="0.98",} 0.001276479
timer_seconds{foo="baz",quantile="0.99",} 0.001276479
timer_seconds{foo="baz",quantile="0.999",} 0.001276479
# HELP timer_seconds Generated from stagemonitor metric import (metric=timer, type=com.codahale.metrics.Timer)
# TYPE timer_seconds summary
timer_seconds_count{foo="bar",} 1.0
timer_seconds_sum{foo="bar",} -1.0
timer_seconds{foo="bar",quantile="0.5",} 0.001102296
timer_seconds{foo="bar",quantile="0.75",} 0.001102296
timer_seconds{foo="bar",quantile="0.95",} 0.001102296
timer_seconds{foo="bar",quantile="0.98",} 0.001102296
timer_seconds{foo="bar",quantile="0.99",} 0.001102296
timer_seconds{foo="bar",quantile="0.999",} 0.001102296
```

**Comment by felixbarny** [comment]
now it should be fine

**Comment by felixbarny** [comment]
fixes #298

**Comment by marcust** [comment]
Ah, ok. At least it is fixed now

**Comment by felixbarny** [comment]
are you ok with my changes?

**Pull request merged**
