### PR TITLE
Add ability to register ElasticsearchRequestTraceReporterInterceptors

### PR DESCRIPTION
**Pull request by felixbarny**
Requested in #124
Allows implementers to customize or omit reporting a request trace to Elasticsearch.
To register one, implement the interface and place the canonical name of the
implementation under `META-INF/services/org.stagemonitor.requestmonitor.reporter.ElasticsearchRequestTraceReporterInterceptor`.

@ryanrupp how do you like the implementation? Would you prefer a registration method instead of the `ServiceLoader` mechanism?

### CODE REVIEW

**Comment by ryanrupp** [comment]
Cool, thanks! I think I'd prefer a registration method similar to how RequestTraceReporters are configured over a service loader because it gives more control over how the object is configured e.g. my interceptor could have some dependencies that I can handle the injection of in my own application and such, then register it. I could probably make either approach work though.

Outside of that only other thoughts are for the sake of API flexibility in the future, the interface would use a single input argument class where any additional context/arguments could be added in a non-breaking way and also could be used to manipulate the return context (e.g. add excluded properties, disable the trace from being reported):

````
void interceptReport(InterceptContext context);

class InterceptContext {
     
    RequestTrace getRequestTrace()
    
    Meter getReportingRate()

    boolean isReported()

    void setReported(boolean reported)

    Collection<String> getExcludedProperties()

    Collection<String> addExcludedProperties(String properties...)
    
}
````

I thought this was a good article in that regard - http://blog.jooq.org/2015/05/21/do-not-make-this-mistake-when-developing-an-spi/

**Comment by felixbarny** [comment]
Great suggestions, thanks. This makes me actually think about reworking all SPIs before 1.0. Have you come across other parts of stagemonitor that would need an overhaul?  

The problem with static registration methods is that the list of implementations also has to be static or that I statically have to get the instance of ERTReporter which does not seem very clean. But you are right, having the ability to register a custom instance is important.

**Comment by ryanrupp** [comment]
I haven't really run into other areas but right now I'm only extending Stagemonitor via the request trace custom parameters and played around with a custom reporter at one point.

**Comment by felixbarny** [comment]
Does it look good to you?

**Comment by felixbarny** [comment]
@ryanrupp do you think you could find some time to review and test this? I just want to make sure that it actually fits your needs.

**Comment by ryanrupp** [comment]
I'll try this out tomorrow.

**Comment by felixbarny** [comment]
I'm merging this now to avoid more merge conflicts. I would still greatly appreciate your feedback. Trying out the latest master just got really easy: https://jitpack.io/#stagemonitor/stagemonitor/master-SNAPSHOT

**Pull request merged**
