### PR TITLE
Add request monitor for Resteasy requests

### PR DESCRIPTION
**Pull request by johnlcox**
Adds support for monitoring Resteasy requests by looking up the jax-rs resource and class to use in determining the request name. This is the implementation for #80.

### CODE REVIEW

**Comment by johnlcox** [comment]
It's possible to startup a jax-rs server for integration tests uses something like tomcat-embed. Based on using tomcat-embed for integration tests on my team, I think it will be a lot more code than the current mocking.

**Comment by felixbarny** [comment]
I see. So it probably would make more sense to create a dedicated integration test project for that. Maybe with spring boot, as integration testing is really easy with it. 

The code looks good so far

**Comment by johnlcox** [comment]
I think a dedicated integration test project would be great. It does look like resteasy can use Undertow [1] to embed in tests, but I'm not seeing an easy way to add configuration or environment variables.

[1] http://docs.jboss.org/resteasy/docs/3.0.4.Final/userguide/html/RESTEasy_Embedded_Container.html

**Comment by felixbarny** [comment]
I'm actually thinking of creating multiple integration test projects. Each project then has the responsibility to test itself either with arquillian or by some other way to start an embedded container during tests. That way I'd be able to test multiple applications, multipe technology sets and multiple servers. Then I just need a script that executes mvn test or gradle test on each project. This also has the advantage that these are essentialy showcase projects of how to integrate stagemonitor.

That link looks promising. What type of configuration or environment variables do you need to set?

**Comment by johnlcox** [comment]
I was looking to set configuration/environment variables for changing the naming strategy and resteasy only request flag to test all permutations like the existing tests do.

**Comment by johnlcox** [comment]
I threw together a very rough integration test [1] using arquillian and it works as long as I comment out the line `Class.forName("org.springframework.web.servlet.HandlerMapping")` in `DefaultMonitoredHttpRequestFactory`.

If I don't comment that line out the test fails because it tries to use the Spring MVC request handler. I'm not too familiar with gradle, so I'm struggling to figure out why the spring-mvc jar is still on my class path for this integration test. If you could take a look and see if there is something obvious to fix the class path issue that would be great.

Once the classpath issue is fixed I can clean it up and add additional tests and add it to the pull request.

[1] https://github.com/johnlcox/stagemonitor/tree/resteasy-integration

**Comment by felixbarny** [comment]
Very nice! Although I would prefer the integration tests to be in a different project. That would also solve the dependency issue in this case. I think this pull request is good enough, but I probably will set up a CLA before merging it. Would that be a problem for you?

**Comment by johnlcox** [comment]
Since the integration tests should be a in a different project and I'm not super familiar with gradle, I'll wait for you to add an integration test project first. Once that is out there I can move/update the resteasy integration tests and send another pull request with those.

A CLA shouldn't be a problem.

**Comment by felixbarny** [comment]
:+1:

**Comment by felixbarny** [comment]
P.S.: a standalone maven based integration test project would be fine as well.

**Comment by felixbarny** [comment]
The CLA is set up: https://github.com/stagemonitor/stagemonitor/blob/master/CONTRIBUTING.md

**Comment by johnlcox** [comment]
This pull request will be under the entity CLA, but out of curiosity, before I sign it, how would I sign the CLA if I was going to make some contributions on behalf of an entity and others as an individual?

**Comment by felixbarny** [comment]
I was asking myself the same question. The easiest way would be to sign both CLAs by including the two different texts into the johnlcox.md file. But then there would be no way to distinguish between entity and individual contributions. The question is wether that matters. I just don't know.

Another option would be to create two different gh accounts and to sign different CLAs with them. 

Or you could ask your emoloyer if it is ok for them if you contribute entirely as a individual. If that's conformable with your employment contract.

**Comment by felixbarny** [comment]
Reading https://odoo-community.org/page/cla it seems that the first option is preferred anyway and that there is no need to distinguish between entity and individual contributions.

**Comment by johnlcox** [comment]
I added the signed CLA with both the individual and entity agreement.

**Comment by felixbarny** [comment]
Thanks again for your awesome contribution! 

What was your experience contributing to this project? Where there any parts of stagemonitor that where particularly hard to read/understand or undocumented?

**Comment by johnlcox** [comment]
It was a pleasant experience making this contribution. I didn't really have any difficulties understanding how things worked within stagemonitor. The bulk of my trouble was with the resteasy documentation, which is unrelated to stagemonitor's documentation.

**Pull request merged**
