### PR TITLE
Skips tagging error as false as that renders in Zipkin's UI as an error

### PR DESCRIPTION
**Pull request by adriancole**
See https://github.com/openzipkin/brave-opentracing/issues/25

### CODE REVIEW

**Comment by felixbarny** [comment]
Hey Adrian, 
Thx for testing stagemonitor and for the pull request!

The problem is that I need the error false flag for the kibana visualization 'Recent Requests by Status': https://github.com/stagemonitor/stagemonitor/wiki/Request-Analysis-Dashboard

However, I could modify the SpanJsonModule to always include the error tag.

**Comment by adriancole** [comment]
ahh interesting! probably should change this PR to a comment then.

I think if using a special-cased zipkin reporter which drops error=false,
it is all good.

**Comment by adriancole** [comment]
>
> However, I could modify the SpanJsonModule to always include the error tag.
>
This would be cool, as it moves it closer to the concern. Also, it is less
fragile for zipkin (selfishly). If we got this PR in, and the UI work in
progress, the zipkin integration looks pretty alright

**Comment by felixbarny** [comment]
The only thing which looks quite quirky still is the visible overflow in the span panel. It would be nice if overflow could be handled in the same way as in the json panel.

**Comment by felixbarny** [comment]
Happy to have you as an official stagemonitor contributor 😄

**Comment by adriancole** [comment]
Me too!

**Pull request merged**
