### PR TITLE
Allow custom host name value

### PR DESCRIPTION
**Pull request by marcust**
We need bigger flexibility for what is written in the hostname, so this patch
adds the possibility to set this via the configuration.

### CODE REVIEW

**Comment by felixbarny** [comment]
:+1: 
May I ask for your use case?

**Comment by marcust** [comment]
Use case is inside Docker containers, Docker uses the container name as hostname, but that actually doesn't give me any information I need and has a far too high cardinality for influxdb.

When is the next release planned?

**Comment by felixbarny** [comment]
Ah, that makes sense. So you are using stagemonitor with InfluxDB? What is your experience with InfluxDB and the integration with it? Have you build your own Grafana dashboards based on the Elasticsearch ones? Or are you using Chronograph?

I plan to release soon, but I want to include #125

**Comment by marcust** [comment]
We're mostly still on 0.18.1, our main issue is/was that we generated far to many metrics, thus we kind of run out of scaling options for InfluxDB, this patch is part of getting that under control.

I build some Grafana dashboards, mostly based on the metrics I needed. When it worked it was quite nice, but as I said, we kind of overwhelmed InfluxDB

**Comment by felixbarny** [comment]
Which version of InfluxDB are you using? Have you tried the new storage engine which they claim to be way more performant and storage efficient? Have you had any problems with the stagemonitor InfluxDB reporter?

**Comment by marcust** [comment]
We're currently using v0.9.6, from what I understand we used the new storage engine but for our use case we kind of still overwhelmed it with data. 

Reporting worked well the last time I really looked into it, next will be to migrate to the newest version of stagemonitor once it is released and see how it works then (including an upgrade to ES 2.0x)

**Pull request merged**
