### PR TITLE
Fix NPE

### PR DESCRIPTION
**Pull request by marcust**
When running against the wrong version of elasticsearch stagemonitor
nullpointers here which masquerades the actual issue.

### CODE REVIEW

**Comment by felixbarny** [comment]
I'm a bit unsure about the usage of the `asText` method. The javadoc says:

```
Method that will return a valid String representation of the container value, if the node is a value node (method isValueNode returns true), otherwise empty String.
```

Maybe the `toString()` method would be better as `error` is probably not a value node but an object node?

**Comment by marcust** [comment]
Well, we were running that against the wrong version of es and that looked like that:
```
{
"index": {
  "_index": "stagemonitor-metrics-2016.06.14",
  "_type": "metrics",
  "_id": null,
  "status": 400,
  "error": "MapperParsingException[mapping [​_default_​]]; nested: IllegalArgumentException[Invalid format: [epoch_millis]: Illegal pattern component: p]; nested: IllegalArgumentException[Illegal pattern component: p]; "
}
}
```

Do you feel safer with toString() anyway?

**Comment by felixbarny** [comment]
Yes, I would feel safer anyway in case of future changes in Elasticsearch.

**Comment by marcust** [comment]
et voilà

**Comment by felixbarny** [comment]
Thanks a lot!

**Pull request merged**
